POST http://localhost:3000/v1/locations/addLocation
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhbGkxQGdtYWlsLmNvbSIsImlhdCI6MTc0NzQ2OTU1NCwiZXhwIjoxNzQ3NTU1OTU0fQ.u57COuwHOXuhwj4P-JQyUXfSY75VOqhpbMqwKincBjI

{
  "name": "aaa",
  "center_lat": 33.0522,
  "center_long": -118.2437
}