@baseURL = {{protocol}}://{{host}}:{{port}}
@basePath = {{baseURL}}/{{version}}
@userRoute = {{basePath}}/user
@route = {{basePath}}/PnP

// REQUESTS


# @name Login
POST {{userRoute}}/login
Content-Type: application/json
Accept: */*

{
    "authenticator": {
        "username": "ali5"
    },
    "password": "pass1!@dSds"
}
###

# @name ADDPnP
POST {{route}}/add-pnp-terms
Content-Type: application/json
Accept: */*
Authorization: Bearer {{Login.response.body.token}}

[
   {
      "heading": "first",
      "content": "We respect your privacy and are committed to protecting your personal data. This policy outlines how we collect, use, and safeguard your information. By using our services, you agree to these terms. We do not share your data with third parties without consent. For more details, contact us at privacy@example.com"
   },
   {
      "heading": "second",
      "content": "We respect your privacy and are committed to protecting your personal data. This policy outlines how we collect, use, and safeguard your information. By using our services, you agree to these terms. We do not share your data with third parties without consent. For more details, contact us at privacy@example.com"
   },
      {
      "heading": "third",
      "content": "We respect your privacy and are committed to protecting your personal data. This policy outlines how we collect, use, and safeguard your information. By using our services, you agree to these terms. We do not share your data with third parties without consent. For more details, contact us at privacy@example.com"
   },
   {
      "heading": "fourth",
      "content": "We respect your privacy and are committed to protecting your personal data. This policy outlines how we collect, use, and safeguard your information. By using our services, you agree to these terms. We do not share your data with third parties without consent. For more details, contact us at privacy@example.com"
   }

]

###

# @name SHOWPnP
POST {{route}}/show-pnp-terms
Content-Type: application/json
Accept: */*
Authorization: Bearer {{Login.response.body.token}}
