POST http://localhost:3000/v1/studies/addToDraft
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhbGkxQGdtYWlsLmNvbSIsImlhdCI6MTc0NzQ2OTU1NCwiZXhwIjoxNzQ3NTU1OTU0fQ.u57COuwHOXuhwj4P-JQyUXfSY75VOqhpbMqwKincBjI

{
  "title": "Area Study",
  "study": "Testing area polygons...",
  "author_id": 1,
  "status": "ai_pending",
  "location_id": 1
}