// FILE VARIABLES

@baseURL = {{protocol}}://{{host}}:{{port}}
@basePath = {{baseURL}}/{{version}}
@userRoute = {{basePath}}/user
@route = {{basePath}}/studies

// REQUESTS

# @name Login
POST {{userRoute}}/login
Content-Type: application/json
Accept: */*

{
    "authenticator": {
        "username": "ali"
    },
    "password": "pass1!@dSds"
}
###

# @name UpdateStudyLocation
PATCH  {{route}}/updateLocation
Content-Type: application/json
Accept: */*
Authorization: Bearer {{Login.response.body.token}}

{
    "location_id" : 2,
    "study_id" : 2
}
###
