// FILE VARIABLES

@baseURL = {{protocol}}://{{host}}:{{port}}
@basePath = {{baseURL}}/{{version}}
@userRoute = {{basePath}}/user
@route = {{basePath}}/GISData

// REQUESTS

# @name Login
POST {{userRoute}}/login
Content-Type: application/json
Accept: */*

{
    "authenticator": {
        "username": "ali"
    },
    "password": "pass1!@dSds"
}
###

# @name AddDataCategory
POST {{route}}/addCategory
Content-Type: application/json
Accept: */*
Authorization: Bearer {{Login.response.body.token}}

{
  "name": "abs",
  "description" : "ali is the GOAT"
}