POST http://localhost:3000/v1/user/register
Content-Type: application/json
Accept: */*

{
    "username": "ali",
    "first_name": "ali",
    "last_name": "ali",
    "email": "ali1@gmail.com",
    "phone": "0909090958",
    "password": "pass1!@dSds"
}