// FILE VARIABLES

@baseURL = {{protocol}}://{{host}}:{{port}}
@basePath = {{baseURL}}/{{version}}
@route = {{basePath}}/user

// REQUESTS

# @name RegisterNewUser
POST {{route}}/register
Content-Type: application/json
Accept: */*

{
    "username": "ali9",
    "first_name": "ali",
    "last_name": "ali",
    "email": "ali9@gmail.com",
    "phone": "0909090958",
    "password": "pass1!@dSds"
}
###

# @name LoginWithEmail
POST {{route}}/login
Content-Type: application/json
Accept: */*

{
    "authenticator": {
        "email": "ali2@gmail.com"
    },
    "password": "pass1!@dSds"
}
###

# @name LoginWithUsername
POST {{route}}/login
Content-Type: application/json
Accept: */*

{
    "authenticator": {
        "username": "ali9"
    },
    "password": "pass1!@dSds"
}
###

# @name deleteAccount
POST {{route}}/delete-account
Content-Type: application/json
Accept: */*
Authorization: Bearer {{LoginWithUsername.response.body.token}}

###