// FILE VARIABLES

@baseURL = {{protocol}}://{{host}}:{{port}}
@basePath = {{baseURL}}/{{version}}
@route = {{basePath}}/test

// REQUESTS

# @name IsServerUp
GET {{route}}/server-up
Content-Type: application/json
Accept: */*
### 
