// FILE VARIABLES

@baseURL = {{protocol}}://{{host}}:{{port}}
@basePath = {{baseURL}}/{{version}}
@userRoute = {{basePath}}/user
@route = {{basePath}}/studies

// REQUESTS

# @name Login
POST {{userRoute}}/login
Content-Type: application/json
Accept: */*

{
    "authenticator": {
        "username": "ali"
    },
    "password": "pass1!@dSds"
}
###

# @name AddStudyDraft
POST {{route}}/addToDraft
Content-Type: application/json
Accept: */*
Authorization: Bearer {{Login.response.body.token}}

{
  "title": "Area Study",
  "study": "Testing area polygons...",
  "author_id": 1,
  "status": "ai_pending",
  "location_id": 1
}
###

# @name SaveStudyWithWarning
PATCH  {{route}}/saveStudy/3
Content-Type: application/json
Accept: */*
Authorization: Bearer {{Login.response.body.token}}
###

# @name UpdateGIS
PATCH {{route}}/updateGIS/3
Content-Type: application/json
Accept: */*
Authorization: Bearer {{{{Login.response.body.token}}}}

[
  {
    "category_id": 1,
    "condition": "abundant",
    "accessibility": "good",
    "locationId": 2,
    "author_id": 1,
    "quantity": {
      "number_val": 150
    }
  }
]
###

# @name UpdateStudyLocation
PATCH  {{route}}/updateLocation
Content-Type: application/json
Accept: */*
Authorization: Bearer {{Login.response.body.token}}

{
    "location_id" : 2,
    "study_id" : 2
}
###
